// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;
using ResearchEngine.Infrastructure;

#nullable disable

namespace ResearchEngine.API.Migrations
{
    [DbContext(typeof(ResearchDbContext))]
    partial class ResearchDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ResearchEngine.Domain.Clarification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now() at time zone 'utc'");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.ToTable("clarifications", (string)null);
                });

            modelBuilder.Entity("ResearchEngine.Domain.Learning", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now() at time zone 'utc'");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EvidenceText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("ImportanceScore")
                        .HasColumnType("real");

                    b.Property<bool>("IsUserProvided")
                        .HasColumnType("boolean");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LearningGroupId")
                        .HasColumnType("uuid");

                    b.Property<string>("QueryHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LearningGroupId");

                    b.HasIndex("JobId", "DeletedAt");

                    b.HasIndex("JobId", "LearningGroupId");

                    b.HasIndex("JobId", "SourceId");

                    b.HasIndex("SourceId", "QueryHash");

                    b.ToTable("learnings", (string)null);
                });

            modelBuilder.Entity("ResearchEngine.Domain.LearningEmbedding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now() at time zone 'utc'");

                    b.Property<Guid>("LearningId")
                        .HasColumnType("uuid");

                    b.Property<Vector>("Vector")
                        .IsRequired()
                        .HasColumnType("vector(1024)");

                    b.HasKey("Id");

                    b.HasIndex("LearningId")
                        .IsUnique();

                    b.HasIndex("Vector")
                        .HasAnnotation("Npgsql:StorageParameter:lists", 100);

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Vector"), "ivfflat");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Vector"), new[] { "vector_cosine_ops" });

                    b.ToTable("learning_embeddings", (string)null);
                });

            modelBuilder.Entity("ResearchEngine.Domain.LearningGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<float>("CanonicalImportanceScore")
                        .HasColumnType("real");

                    b.Property<string>("CanonicalText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now() at time zone 'utc'");

                    b.Property<int>("DistinctSourceCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid");

                    b.Property<int>("MemberCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now() at time zone 'utc'");

                    b.HasKey("Id");

                    b.HasIndex("JobId", "UpdatedAt");

                    b.ToTable("learning_groups", (string)null);
                });

            modelBuilder.Entity("ResearchEngine.Domain.LearningGroupEmbedding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now() at time zone 'utc'");

                    b.Property<Guid>("LearningGroupId")
                        .HasColumnType("uuid");

                    b.Property<Vector>("Vector")
                        .IsRequired()
                        .HasColumnType("vector(1024)");

                    b.HasKey("Id");

                    b.HasIndex("LearningGroupId")
                        .IsUnique();

                    b.HasIndex("Vector")
                        .HasAnnotation("Npgsql:StorageParameter:lists", 100);

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Vector"), "ivfflat");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Vector"), new[] { "vector_cosine_ops" });

                    b.ToTable("learning_group_embeddings", (string)null);
                });

            modelBuilder.Entity("ResearchEngine.Domain.ResearchEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("SynthesisId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("JobId", "SynthesisId");

                    b.ToTable("research_events", (string)null);
                });

            modelBuilder.Entity("ResearchEngine.Domain.ResearchJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Breadth")
                        .HasColumnType("integer");

                    b.Property<string>("CancelReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("CancelRequested")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset?>("CancelRequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ChatModelName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now() at time zone 'utc'");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("Depth")
                        .HasColumnType("integer");

                    b.Property<string>("EmbeddingModelName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("HangfireJobId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Query")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Region")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TargetLanguage")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now() at time zone 'utc'");

                    b.HasKey("Id");

                    b.HasIndex("DeletedAt");

                    b.HasIndex("Status");

                    b.ToTable("research_jobs", (string)null);
                });

            modelBuilder.Entity("ResearchEngine.Domain.Source", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now() at time zone 'utc'");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<string>("Language")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Region")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Title")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("ContentHash");

                    b.HasIndex("JobId", "DeletedAt");

                    b.HasIndex("JobId", "Reference")
                        .IsUnique();

                    b.ToTable("sources", (string)null);
                });

            modelBuilder.Entity("ResearchEngine.Domain.Synthesis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ChatModelName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now() at time zone 'utc'");

                    b.Property<string>("EmbeddingModelName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Instructions")
                        .HasColumnType("text");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid");

                    b.Property<string>("Outline")
                        .HasColumnType("text");

                    b.Property<Guid?>("ParentSynthesisId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ParentSynthesisId");

                    b.HasIndex("Status");

                    b.HasIndex("JobId", "CreatedAt");

                    b.ToTable("syntheses", (string)null);
                });

            modelBuilder.Entity("ResearchEngine.Domain.SynthesisLearningOverride", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now() at time zone 'utc'");

                    b.Property<bool?>("Excluded")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LearningId")
                        .HasColumnType("uuid");

                    b.Property<bool?>("Pinned")
                        .HasColumnType("boolean");

                    b.Property<float?>("ScoreOverride")
                        .HasColumnType("real");

                    b.Property<Guid>("SynthesisId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LearningId");

                    b.HasIndex("SynthesisId", "LearningId")
                        .IsUnique();

                    b.ToTable("synthesis_learning_overrides", (string)null);
                });

            modelBuilder.Entity("ResearchEngine.Domain.SynthesisSection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentMarkdown")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now() at time zone 'utc'");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<int>("Index")
                        .HasColumnType("integer");

                    b.Property<bool>("IsConclusion")
                        .HasColumnType("boolean");

                    b.Property<Guid>("SectionKey")
                        .HasColumnType("uuid");

                    b.Property<string>("Summary")
                        .HasMaxLength(20000)
                        .HasColumnType("character varying(20000)");

                    b.Property<Guid>("SynthesisId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("SynthesisId", "Index")
                        .IsUnique();

                    b.HasIndex("SynthesisId", "SectionKey")
                        .IsUnique();

                    b.ToTable("synthesis_sections", (string)null);
                });

            modelBuilder.Entity("ResearchEngine.Domain.SynthesisSourceOverride", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now() at time zone 'utc'");

                    b.Property<bool?>("Excluded")
                        .HasColumnType("boolean");

                    b.Property<bool?>("Pinned")
                        .HasColumnType("boolean");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SynthesisId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SourceId");

                    b.HasIndex("SynthesisId", "SourceId")
                        .IsUnique();

                    b.ToTable("synthesis_source_overrides", (string)null);
                });

            modelBuilder.Entity("ResearchEngine.Domain.Clarification", b =>
                {
                    b.HasOne("ResearchEngine.Domain.ResearchJob", "Job")
                        .WithMany("Clarifications")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("ResearchEngine.Domain.Learning", b =>
                {
                    b.HasOne("ResearchEngine.Domain.ResearchJob", "Job")
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ResearchEngine.Domain.LearningGroup", "Group")
                        .WithMany("Learnings")
                        .HasForeignKey("LearningGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ResearchEngine.Domain.Source", "Source")
                        .WithMany("Learnings")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Job");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("ResearchEngine.Domain.LearningEmbedding", b =>
                {
                    b.HasOne("ResearchEngine.Domain.Learning", "Learning")
                        .WithOne("Embedding")
                        .HasForeignKey("ResearchEngine.Domain.LearningEmbedding", "LearningId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Learning");
                });

            modelBuilder.Entity("ResearchEngine.Domain.LearningGroup", b =>
                {
                    b.HasOne("ResearchEngine.Domain.ResearchJob", "Job")
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("ResearchEngine.Domain.LearningGroupEmbedding", b =>
                {
                    b.HasOne("ResearchEngine.Domain.LearningGroup", "Group")
                        .WithOne("Embedding")
                        .HasForeignKey("ResearchEngine.Domain.LearningGroupEmbedding", "LearningGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("ResearchEngine.Domain.ResearchEvent", b =>
                {
                    b.HasOne("ResearchEngine.Domain.ResearchJob", "Job")
                        .WithMany("Events")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("ResearchEngine.Domain.Source", b =>
                {
                    b.HasOne("ResearchEngine.Domain.ResearchJob", "Job")
                        .WithMany("Sources")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("ResearchEngine.Domain.Synthesis", b =>
                {
                    b.HasOne("ResearchEngine.Domain.ResearchJob", "Job")
                        .WithMany("Syntheses")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ResearchEngine.Domain.Synthesis", "ParentSynthesis")
                        .WithMany("Children")
                        .HasForeignKey("ParentSynthesisId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Job");

                    b.Navigation("ParentSynthesis");
                });

            modelBuilder.Entity("ResearchEngine.Domain.SynthesisLearningOverride", b =>
                {
                    b.HasOne("ResearchEngine.Domain.Learning", "Learning")
                        .WithMany()
                        .HasForeignKey("LearningId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ResearchEngine.Domain.Synthesis", "Synthesis")
                        .WithMany()
                        .HasForeignKey("SynthesisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Learning");

                    b.Navigation("Synthesis");
                });

            modelBuilder.Entity("ResearchEngine.Domain.SynthesisSection", b =>
                {
                    b.HasOne("ResearchEngine.Domain.Synthesis", "Synthesis")
                        .WithMany("Sections")
                        .HasForeignKey("SynthesisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Synthesis");
                });

            modelBuilder.Entity("ResearchEngine.Domain.SynthesisSourceOverride", b =>
                {
                    b.HasOne("ResearchEngine.Domain.Source", "Source")
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ResearchEngine.Domain.Synthesis", "Synthesis")
                        .WithMany()
                        .HasForeignKey("SynthesisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Source");

                    b.Navigation("Synthesis");
                });

            modelBuilder.Entity("ResearchEngine.Domain.Learning", b =>
                {
                    b.Navigation("Embedding")
                        .IsRequired();
                });

            modelBuilder.Entity("ResearchEngine.Domain.LearningGroup", b =>
                {
                    b.Navigation("Embedding")
                        .IsRequired();

                    b.Navigation("Learnings");
                });

            modelBuilder.Entity("ResearchEngine.Domain.ResearchJob", b =>
                {
                    b.Navigation("Clarifications");

                    b.Navigation("Events");

                    b.Navigation("Sources");

                    b.Navigation("Syntheses");
                });

            modelBuilder.Entity("ResearchEngine.Domain.Source", b =>
                {
                    b.Navigation("Learnings");
                });

            modelBuilder.Entity("ResearchEngine.Domain.Synthesis", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Sections");
                });
#pragma warning restore 612, 618
        }
    }
}
