// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;
using ResearchApi.Infrastructure;

#nullable disable

namespace ResearchApi.Migrations
{
    [DbContext(typeof(ResearchDbContext))]
    [Migration("20251221111839_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ResearchApi.Domain.Clarification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now() at time zone 'utc'");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.ToTable("clarifications", (string)null);
                });

            modelBuilder.Entity("ResearchApi.Domain.Learning", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now() at time zone 'utc'");

                    b.Property<string>("EvidenceText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("ImportanceScore")
                        .HasColumnType("real");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid");

                    b.Property<string>("QueryHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("JobId", "SourceId");

                    b.HasIndex("SourceId", "QueryHash");

                    b.ToTable("learnings", (string)null);
                });

            modelBuilder.Entity("ResearchApi.Domain.LearningEmbedding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now() at time zone 'utc'");

                    b.Property<Guid>("LearningId")
                        .HasColumnType("uuid");

                    b.Property<Vector>("Vector")
                        .IsRequired()
                        .HasColumnType("vector(1024)");

                    b.HasKey("Id");

                    b.HasIndex("LearningId")
                        .IsUnique();

                    b.HasIndex("Vector")
                        .HasAnnotation("Npgsql:StorageParameter:lists", 100);

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Vector"), "ivfflat");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Vector"), new[] { "vector_cosine_ops" });

                    b.ToTable("learning_embeddings", (string)null);
                });

            modelBuilder.Entity("ResearchApi.Domain.ResearchEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.ToTable("research_events", (string)null);
                });

            modelBuilder.Entity("ResearchApi.Domain.ResearchJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Breadth")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now() at time zone 'utc'");

                    b.Property<int>("Depth")
                        .HasColumnType("integer");

                    b.Property<string>("Query")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Region")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TargetLanguage")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now() at time zone 'utc'");

                    b.HasKey("Id");

                    b.ToTable("research_jobs", (string)null);
                });

            modelBuilder.Entity("ResearchApi.Domain.Source", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now() at time zone 'utc'");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid");

                    b.Property<string>("Language")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Region")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Title")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasIndex("ContentHash");

                    b.HasIndex("JobId", "Url")
                        .IsUnique();

                    b.ToTable("sources", (string)null);
                });

            modelBuilder.Entity("ResearchApi.Domain.Synthesis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now() at time zone 'utc'");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Instructions")
                        .HasColumnType("text");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid");

                    b.Property<string>("Outline")
                        .HasColumnType("text");

                    b.Property<Guid?>("ParentSynthesisId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReportMarkdown")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ParentSynthesisId");

                    b.HasIndex("Status");

                    b.HasIndex("JobId", "CreatedAt");

                    b.ToTable("syntheses", (string)null);
                });

            modelBuilder.Entity("ResearchApi.Domain.SynthesisLearningOverride", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now() at time zone 'utc'");

                    b.Property<bool?>("Excluded")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LearningId")
                        .HasColumnType("uuid");

                    b.Property<bool?>("Pinned")
                        .HasColumnType("boolean");

                    b.Property<float?>("ScoreOverride")
                        .HasColumnType("real");

                    b.Property<Guid>("SynthesisId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LearningId");

                    b.HasIndex("SynthesisId", "LearningId")
                        .IsUnique();

                    b.ToTable("synthesis_learning_overrides", (string)null);
                });

            modelBuilder.Entity("ResearchApi.Domain.SynthesisSourceOverride", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now() at time zone 'utc'");

                    b.Property<bool?>("Excluded")
                        .HasColumnType("boolean");

                    b.Property<bool?>("Pinned")
                        .HasColumnType("boolean");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SynthesisId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SourceId");

                    b.HasIndex("SynthesisId", "SourceId")
                        .IsUnique();

                    b.ToTable("synthesis_source_overrides", (string)null);
                });

            modelBuilder.Entity("ResearchApi.Domain.Clarification", b =>
                {
                    b.HasOne("ResearchApi.Domain.ResearchJob", "Job")
                        .WithMany("Clarifications")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("ResearchApi.Domain.Learning", b =>
                {
                    b.HasOne("ResearchApi.Domain.ResearchJob", "Job")
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ResearchApi.Domain.Source", "Source")
                        .WithMany("Learnings")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("ResearchApi.Domain.LearningEmbedding", b =>
                {
                    b.HasOne("ResearchApi.Domain.Learning", "Learning")
                        .WithOne("Embedding")
                        .HasForeignKey("ResearchApi.Domain.LearningEmbedding", "LearningId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Learning");
                });

            modelBuilder.Entity("ResearchApi.Domain.ResearchEvent", b =>
                {
                    b.HasOne("ResearchApi.Domain.ResearchJob", "Job")
                        .WithMany("Events")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("ResearchApi.Domain.Source", b =>
                {
                    b.HasOne("ResearchApi.Domain.ResearchJob", "Job")
                        .WithMany("Sources")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("ResearchApi.Domain.Synthesis", b =>
                {
                    b.HasOne("ResearchApi.Domain.ResearchJob", "Job")
                        .WithMany("Syntheses")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ResearchApi.Domain.Synthesis", "ParentSynthesis")
                        .WithMany("Children")
                        .HasForeignKey("ParentSynthesisId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Job");

                    b.Navigation("ParentSynthesis");
                });

            modelBuilder.Entity("ResearchApi.Domain.SynthesisLearningOverride", b =>
                {
                    b.HasOne("ResearchApi.Domain.Learning", "Learning")
                        .WithMany()
                        .HasForeignKey("LearningId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ResearchApi.Domain.Synthesis", "Synthesis")
                        .WithMany()
                        .HasForeignKey("SynthesisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Learning");

                    b.Navigation("Synthesis");
                });

            modelBuilder.Entity("ResearchApi.Domain.SynthesisSourceOverride", b =>
                {
                    b.HasOne("ResearchApi.Domain.Source", "Source")
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ResearchApi.Domain.Synthesis", "Synthesis")
                        .WithMany()
                        .HasForeignKey("SynthesisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Source");

                    b.Navigation("Synthesis");
                });

            modelBuilder.Entity("ResearchApi.Domain.Learning", b =>
                {
                    b.Navigation("Embedding")
                        .IsRequired();
                });

            modelBuilder.Entity("ResearchApi.Domain.ResearchJob", b =>
                {
                    b.Navigation("Clarifications");

                    b.Navigation("Events");

                    b.Navigation("Sources");

                    b.Navigation("Syntheses");
                });

            modelBuilder.Entity("ResearchApi.Domain.Source", b =>
                {
                    b.Navigation("Learnings");
                });

            modelBuilder.Entity("ResearchApi.Domain.Synthesis", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
