apiVersion: v1
kind: Secret
metadata:
  name: research-single-host-secrets
type: Opaque
stringData:
  ChatConfig__ApiKey: "Y6BksOt4+wdRsAJwZIrFV3Yo37fdl+2tPScWnfaT9S+IXekwc6HgcJqQVvfPpoD4"
  EmbeddingConfig__ApiKey: "ollama"
  AuthenticationOptions__ApiKeys__0: "RYCQlDNSFnJgUrOIZdnh4mlOghdkzhCntgeDjsJqCYFz7tou1F1bZi8oNJ4C0hav"
  RESEARCH_POSTGRES_DB: "research"
  RESEARCH_POSTGRES_USER: "research"
  RESEARCH_POSTGRES_PASSWORD: "research-password"
  RESEARCH_CONNECTION_STRING: "Host=127.0.0.1;Port=5432;Database=research;Username=research;Password=research-password"
  CRAWL_POSTGRES_DB: "firecrawl"
  CRAWL_POSTGRES_USER: "firecrawl"
  CRAWL_POSTGRES_PASSWORD: "firecrawl-password"
  CRAWL_DATABASE_URL: "postgresql://firecrawl:firecrawl-password@127.0.0.1:5432/firecrawl?sslmode=disable"
  FIRE_CRAWL_API_KEY: "WkMuaTD254l96hxmUIKrATIAFNyRK0UiMss12ayDO+A="
  BULL_AUTH_KEY: "28d4f12a03a9476ba93e59e3fa752623e090f9798ff94d1089dd5f706ae8213f"
  SEARXNG_SECRET: "fc57350014683f0e6e5938408f9742ccc584ceb561476e682af398e5d807dc78"
